classDiagram
    class Eleitor {
        - String nome
        - int anoNascimento
        + Eleitor(String nome, int anoNascimento)
        + getNome() String
        + getAnoNascimento() int
        + calcularIdade() int
        + calcularTipoEleitor() String
    }
