classDiagram
    class Cilindro {
        - double raio
        - double altura
        + Cilindro(double raio, double altura)
        + getRaio() double
        + getAltura() double
        + calcularAreaLateral() double
        + calcularAreaTotal() double
        + calcularVolume() double
    }
