classDiagram
    class Retangulo {
        - double comprimento
        - double largura
        + Retangulo(double comprimento, double largura)
        + getComprimento() double
        + getLargura() double
        + calcularArea() double
        + calcularPerimetro() double
    }
