classDiagram
    class Paralelepipedo {
        - double altura
        - double largura
        - double comprimento
        + Paralelepipedo(double altura, double largura, double comprimento)
        + getAltura() double
        + getLargura() double
        + getComprimento() double
        + calcularVolume() double
        + calcularArea() double
    }
