version: '3.8'

services:
  clinica-db:
    image: postgres:15-alpine
    container_name: clinica-universitaria-db
    environment:
      POSTGRES_DB: clinica_universitaria
      POSTGRES_USER: clinica_user
      POSTGRES_PASSWORD: clinica_pass
    ports:
      - "5433:5432"  # Usando porta 5433 para evitar conflito
    volumes:
      - clinica_pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - clinica-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clinica_user -d clinica_universitaria"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Opcional: pgAdmin para administração do banco
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: clinica-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@clinica.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    networks:
      - clinica-network
    depends_on:
      - clinica-db
    restart: unless-stopped

networks:
  clinica-network:
    driver: bridge

volumes:
  clinica_pgdata:
    driver: local
