classDiagram
    class Cone {
        - double raio
        - double altura
        + Cone(double raio, double altura)
        + getRaio() double
        + getAltura() double
        + calcularGeratriz() double
        + calcularAreaLateral() double
        + calcularAreaTotal() double
        + calcularVolume() double
    }
