classDiagram
    class Esfera {
        - double raio
        + Esfera(double raio)
        + getRaio() double
        + setRaio(double raio) void
        + calcularArea() double
        + calcularVolume() double
    }
